# Generated by Django 4.2.30 on 2026-07-11 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('core', '0002_alter_utilisateur_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrivage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_bon', models.CharField(max_length=50, unique=True)),
                ('date_arrivage', models.DateField()),
                ('numero_facture', models.CharField(blank=True, max_length=50)),
                ('montant_facture', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivages', to='core.agence')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivages_crees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivages', to='catalogue.fournisseur')),
            ],
            options={
                'ordering': ['-date_arrivage'],
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('en_stock', 'En stock'), ('vendue', 'Vendue'), ('transferee', 'Transferee')], default='en_stock', max_length=20)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motos', to='core.agence')),
                ('arrivage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motos', to='stock.arrivage')),
                ('couleur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motos', to='catalogue.couleur')),
                ('type_moto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motos', to='catalogue.typemoto')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueMoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(choices=[('arrivage', 'Arrivage'), ('vente', 'Vente'), ('transfert', 'Transfert'), ('sav', 'SAV')], max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_evenement', models.DateTimeField(auto_now_add=True)),
                ('agence_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.agence')),
                ('agence_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.agence')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='stock.moto')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evenement historique moto',
                'verbose_name_plural': 'Historique motos',
                'ordering': ['-date_evenement'],
            },
        ),
    ]
