# Generated by Django 4.2.30 on 2026-07-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='immatriculation',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
