# Generated by Django 4.2.30 on 2026-07-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_moto_immatriculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiquemoto',
            name='type_evenement',
            field=models.CharField(choices=[('arrivage', 'Arrivage'), ('vente', 'Vente'), ('transfert', 'Transfert'), ('sav', 'SAV'), ('depot', 'Envoi en depot'), ('retour_depot', 'Retour de depot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='moto',
            name='statut',
            field=models.CharField(choices=[('en_stock', 'En stock'), ('vendue', 'Vendue'), ('transferee', 'Transferee'), ('en_depot', 'En depot')], default='en_stock', max_length=20),
        ),
    ]
