# Generated by Django 4.2.30 on 2026-08-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_historiquemoto_type_evenement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivage',
            name='fichier_cmc',
            field=models.FileField(blank=True, null=True, upload_to='cmc/'),
        ),
    ]
