# Generated by Django 4.2.30 on 2026-08-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_arrivage_fichier_cmc'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivage',
            name='en_depot',
            field=models.BooleanField(default=False, help_text='Motos recues en depot chez le fournisseur, a regler seulement une fois vendues.'),
        ),
    ]
