# Generated by Django 4.2.30 on 2026-07-11 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_utilisateur_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('loyer', 'Loyer'), ('salaire', 'Salaire'), ('carburant', 'Carburant'), ('entretien', 'Entretien'), ('fourniture', 'Fourniture'), ('transport', 'Transport'), ('autre', 'Autre')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs_depenses/')),
                ('date_depense', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='core.agence')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_depense'],
            },
        ),
    ]
