# Generated by Django 4.2.30 on 2026-07-11 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('core', '0002_alter_utilisateur_options'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='core.agence')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('validee', 'Validee'), ('annulee', 'Annulee')], default='validee', max_length=20)),
                ('date_facture', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='core.agence')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='facturation.client')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_facture'],
            },
        ),
        migrations.CreateModel(
            name='Quittance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('quittance', 'Quittance'), ('cmc', 'CMC')], max_length=20)),
                ('numero', models.CharField(blank=True, max_length=50)),
                ('date_soumission', models.DateField(auto_now_add=True)),
                ('date_retrait', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quittances', to='facturation.facture')),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.facture')),
                ('modele_casque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogue.modelecasque')),
                ('moto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ligne_facture', to='stock.moto')),
            ],
        ),
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_declaration', models.CharField(blank=True, max_length=50)),
                ('date_declaration', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('facture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaration', to='facturation.facture')),
            ],
        ),
        migrations.CreateModel(
            name='CarteGrise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_dossier', models.CharField(blank=True, max_length=50)),
                ('date_soumission', models.DateField(auto_now_add=True)),
                ('date_retrait', models.DateField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('facture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carte_grise', to='facturation.facture')),
            ],
        ),
    ]
