# Generated by Django 4.2.30 on 2026-07-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='segment',
            field=models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('revendeur', 'Revendeur')], default='standard', max_length=20),
        ),
    ]
