# Generated by Django 4.2.30 on 2026-07-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_client_segment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartegrise',
            options={'ordering': ['-date_soumission', '-id']},
        ),
    ]
