# Generated by Django 4.2.30 on 2026-07-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0003_alter_cartegrise_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='remarque',
            field=models.TextField(blank=True),
        ),
    ]
