# Generated by Django 4.2.30 on 2026-07-30 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0003_alter_historiquemoto_type_evenement_and_more'),
        ('core', '0002_alter_utilisateur_options'),
        ('facturation', '0004_facture_remarque'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvoiDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envois_depot', to='core.agence')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envois_depot', to='facturation.client')),
                ('envoye_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envois_depot_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='DepotVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('retournee', 'Retournee'), ('vendue', 'Vendue')], default='en_cours', max_length=20)),
                ('date_resolution', models.DateTimeField(blank=True, null=True)),
                ('envoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='facturation.envoidepot')),
                ('ligne_facture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depot_origine', to='facturation.lignefacture')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depots', to='stock.moto')),
                ('resolu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depots_resolus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
