# Generated by Django 4.2.30 on 2026-07-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0005_envoidepot_depotvente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartegrise',
            name='date_reception',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartegrise',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='cartes_grises/'),
        ),
        migrations.AddField(
            model_name='cartegrise',
            name='retirer_nom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cartegrise',
            name='retirer_telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='quittance',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='quittances/'),
        ),
        migrations.AddField(
            model_name='quittance',
            name='retirer_nom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='quittance',
            name='retirer_telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cartegrise',
            name='date_retrait',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quittance',
            name='date_retrait',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
