# Generated by Django 4.2.30 on 2026-08-03 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturation', '0006_cartegrise_date_reception_cartegrise_fichier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures_annulees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
