# Generated by Django 4.2.30 on 2026-08-04 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0007_facture_annule_par_facture_date_annulation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartegrise',
            name='ligne_facture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carte_grise', to='facturation.lignefacture'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='avec_carte_grise',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartegrise',
            name='facture',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carte_grise', to='facturation.facture'),
        ),
    ]
