# Generated by Django 4.2.30 on 2026-08-04 17:32

from django.db import migrations


def migrer_vers_ligne_facture(apps, schema_editor):
    CarteGrise = apps.get_model('facturation', 'CarteGrise')
    for carte_grise in CarteGrise.objects.select_related('facture').all():
        ligne = (
            carte_grise.facture.lignes.filter(moto__isnull=False).order_by('id').first()
            or carte_grise.facture.lignes.order_by('id').first()
        )
        if ligne is not None:
            carte_grise.ligne_facture = ligne
            carte_grise.save(update_fields=['ligne_facture'])


def revenir_vers_facture(apps, schema_editor):
    CarteGrise = apps.get_model('facturation', 'CarteGrise')
    for carte_grise in CarteGrise.objects.select_related('ligne_facture').all():
        if carte_grise.ligne_facture is not None:
            carte_grise.facture_id = carte_grise.ligne_facture.facture_id
            carte_grise.save(update_fields=['facture'])


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0008_cartegrise_ligne_facture_step1'),
    ]

    operations = [
        migrations.RunPython(migrer_vers_ligne_facture, revenir_vers_facture),
    ]
