# Generated by Django 4.2.30 on 2026-08-04 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_arrivage_en_depot'),
        ('facturation', '0010_cartegrise_ligne_facture_step2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignefacture',
            name='moto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_facture', to='stock.moto'),
        ),
    ]
