# Generated by Django 4.2.30 on 2026-07-11 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('duree_mois', models.PositiveIntegerField(default=12)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garanties_creees', to=settings.AUTH_USER_MODEL)),
                ('moto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garantie', to='stock.moto')),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entretien', models.CharField(choices=[('vidange', 'Vidange'), ('revision_generale', 'Revision generale'), ('controle', 'Controle'), ('autre', 'Autre')], max_length=30)),
                ('date_prevue', models.DateField()),
                ('date_realisee', models.DateField(blank=True, null=True)),
                ('kilometrage', models.PositiveIntegerField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entretiens_crees', to=settings.AUTH_USER_MODEL)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='stock.moto')),
            ],
            options={
                'ordering': ['date_prevue'],
            },
        ),
    ]
