# Generated by Django 4.2.30 on 2026-07-28 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_utilisateur_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caisse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortieCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motif', models.CharField(choices=[('versement_banque', 'Versement en banque'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date_sortie', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorties_caisse', to='core.agence')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sorties_caisse_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_sortie'],
            },
        ),
        migrations.CreateModel(
            name='SessionCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_session', models.DateField()),
                ('montant_ouverture', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_fermeture', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_ouverture', models.DateTimeField(auto_now_add=True)),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_caisse', to='core.agence')),
                ('ferme_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_caisse_fermees', to=settings.AUTH_USER_MODEL)),
                ('ouvert_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_caisse_ouvertes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_session'],
                'unique_together': {('agence', 'date_session')},
            },
        ),
    ]
