# Generated by Django 4.2.30 on 2026-08-03 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caisse', '0002_sortiecaisse_sessioncaisse'),
    ]

    operations = [
        migrations.AddField(
            model_name='versement',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versements_annules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='versement',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='versement',
            name='statut',
            field=models.CharField(choices=[('valide', 'Valide'), ('annule', 'Annule')], default='valide', max_length=20),
        ),
    ]
