# Generated by Django 4.2.30 on 2026-08-04 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_typemoto_code'),
        ('caisse', '0003_versement_annule_par_versement_date_annulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortiecaisse',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reglements', to='catalogue.fournisseur'),
        ),
        migrations.AlterField(
            model_name='sortiecaisse',
            name='motif',
            field=models.CharField(choices=[('versement_banque', 'Versement en banque'), ('reglement_fournisseur', 'Reglement fournisseur'), ('autre', 'Autre')], default='autre', max_length=25),
        ),
    ]
