# Generated by Django 4.2.30 on 2026-07-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typemoto',
            name='seuil_alerte',
            field=models.PositiveIntegerField(default=3, help_text="Quantite minimale en stock avant declenchement d'une alerte"),
        ),
    ]
