# Generated by Django 4.2.30 on 2026-07-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_typemoto_seuil_alerte'),
    ]

    operations = [
        migrations.AddField(
            model_name='typemoto',
            name='code',
            field=models.CharField(blank=True, help_text='Prefixe du numero de serie/chassis pour ce type', max_length=20),
        ),
    ]
