# Generated by Django 4.2.30 on 2026-07-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateur',
            options={'ordering': ['username']},
        ),
    ]
