# Generated by Django 4.2.30 on 2026-07-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_utilisateur_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='agence',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='agence',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='agences_logos/'),
        ),
        migrations.AddField(
            model_name='agence',
            name='nif',
            field=models.CharField(blank=True, help_text="Numero d'identification fiscale", max_length=50),
        ),
        migrations.AddField(
            model_name='agence',
            name='nom_commercial',
            field=models.CharField(blank=True, help_text='Nom affiche sur les documents imprimes (sinon le Nom est utilise).', max_length=150),
        ),
        migrations.AddField(
            model_name='agence',
            name='rccm',
            field=models.CharField(blank=True, help_text='Numero de registre de commerce', max_length=50),
        ),
        migrations.AddField(
            model_name='agence',
            name='site_web',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
