# Generated by Django 4.2.30 on 2026-08-05 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_agence_email_agence_logo_agence_nif_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur_username', models.CharField(blank=True, max_length=150)),
                ('methode', models.CharField(choices=[('creation', 'Creation'), ('modification', 'Modification'), ('suppression', 'Suppression'), ('action', 'Action')], max_length=20)),
                ('ressource', models.CharField(blank=True, max_length=100)),
                ('objet_id', models.CharField(blank=True, max_length=50)),
                ('chemin', models.CharField(max_length=255)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('agence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.agence')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
    ]
